#!/bin/sh

WDIR=/Users/srikris/EMC/madlib


if [ "$1" == "c" ]; then
	$WDIR/build/src/bin/madpack -p greenplum install-check
elif [ "$1" == "i" ]; then
	$WDIR/build/src/bin/madpack -p greenplum install
else
	$WDIR/build/src/bin/madpack -p greenplum reinstall
fi
