DATA_built = decision-tree.sql decision-tree-drop.sql

MODULE_big = decision-tree
PGXS := $(shell pg_config --pgxs)
include $(PGXS)
include config.mk
#CC=gcc -no-cpp-precomp -m64
#CC=gcc -no-cpp-precomp -m32
