DATA_built = decision_tree.sql decision_tree_drop.sql

MODULES = DTree_stat
PGXS := $(shell pg_config --pgxs)
include $(PGXS)
include config.mk
#CC=gcc -no-cpp-precomp -m64
#CC=gcc -no-cpp-precomp -m32
