SELECT
fmcount(fyq),
fmcount(cfda_program_num),
fmcount(sai_number),
fmcount(recipient_name),
fmcount(recipient_city_code),
fmcount(recipient_city_name),
fmcount(recipient_county_code),
fmcount(recipient_county_name),
fmcount(recipient_state_code),
fmcount(recipient_zip),
fmcount(recipient_type),
fmcount(action_type),
fmcount(recipient_cong_district),
fmcount(agency_code),
fmcount(federal_award_id),
fmcount(federal_award_mod),
fmcount(fed_funding_amount),
fmcount(non_fed_funding_amount),
fmcount(total_funding_amount),
fmcount(obligation_action_date),
fmcount(starting_date),
fmcount(ending_date),
fmcount(assistance_type),
fmcount(record_type),
fmcount(correction_late_ind),
fmcount(fyq_correction),
fmcount(principal_place_code),
fmcount(principal_place_state),
fmcount(principal_place_cc),
fmcount(principal_place_zip),
fmcount(principal_place_cd),
fmcount(cfda_program_title),
fmcount(agency_name),
fmcount(recipient_state_name),
fmcount(project_description),
fmcount(duns_no),
fmcount(duns_conf_code),
fmcount(progsrc_agen_code),
fmcount(progsrc_acnt_code),
fmcount(progsrc_subacnt_code),
fmcount(receip_addr1),
fmcount(progsrc_subacnt_code),
fmcount(receip_addr1),
fmcount(receip_addr2),
fmcount(receip_addr3),
fmcount(face_loan_guran),
fmcount(orig_sub_guran),
fmcount(parent_duns_no),
fmcount(record_id),
fmcount(fiscal_year),
fmcount(principal_place_state_code),
fmcount(award_id),
fmcount(recip_cat_type),
fmcount(asst_cat_type),
fmcount(recipient_cd),
fmcount(maj_agency_cat),
fmcount(mod_name),
fmcount(recip_id),
fmcount(business_identifier),
fmcount(rec_flag),
fmcount(recipient_country_code),
fmcount(principal_place_country_code),
fmcount(uri),
fmcount(lookup_parent_rec_id),
fmcount(corr_name),
fmcount(corr_mod_name),
fmcount(correct_state_code),
fmcount(mod_eeduns),
fmcount(mod_parent),
fmcount(parent_id),
fmcount(agency_submission_date),
fmcount(recipient_loc_mismatch_flag),
fmcount(pop_loc_mismatch_flag),
fmcount(duns_mismatch_flag),
fmcount(cfda_mismatch_flag),
fmcount(eeparentduns),
fmcount(parentcompany),
fmcount(rei_created_date),
fmcount(rei_updated_date)
FROM faads_main;

SELECT
count(distinct fyq),
count(distinct cfda_program_num),
count(distinct sai_number),
count(distinct recipient_name),
count(distinct recipient_city_code),
count(distinct recipient_city_name),
count(distinct recipient_county_code),
count(distinct recipient_county_name),
count(distinct recipient_state_code),
count(distinct recipient_zip),
count(distinct recipient_type),
count(distinct action_type),
count(distinct recipient_cong_district),
count(distinct agency_code),
count(distinct federal_award_id),
count(distinct federal_award_mod),
count(distinct fed_funding_amount),
count(distinct non_fed_funding_amount),
count(distinct total_funding_amount),
count(distinct obligation_action_date),
count(distinct starting_date),
count(distinct ending_date),
count(distinct assistance_type),
count(distinct record_type),
count(distinct correction_late_ind),
count(distinct fyq_correction),
count(distinct principal_place_code),
count(distinct principal_place_state),
count(distinct principal_place_cc),
count(distinct principal_place_zip),
count(distinct principal_place_cd),
count(distinct cfda_program_title),
count(distinct agency_name),
count(distinct recipient_state_name),
count(distinct project_description),
count(distinct duns_no),
count(distinct duns_conf_code),
count(distinct progsrc_agen_code),
count(distinct progsrc_acnt_code),
count(distinct progsrc_subacnt_code),
count(distinct receip_addr1),
count(distinct progsrc_subacnt_code),
count(distinct receip_addr1),
count(distinct receip_addr2),
count(distinct receip_addr3),
count(distinct face_loan_guran),
count(distinct orig_sub_guran),
count(distinct parent_duns_no),
count(distinct record_id),
count(distinct fiscal_year),
count(distinct principal_place_state_code),
count(distinct award_id),
count(distinct recip_cat_type),
count(distinct asst_cat_type),
count(distinct recipient_cd),
count(distinct maj_agency_cat),
count(distinct mod_name),
count(distinct recip_id),
count(distinct business_identifier),
count(distinct rec_flag),
count(distinct recipient_country_code),
count(distinct principal_place_country_code),
count(distinct uri),
count(distinct lookup_parent_rec_id),
count(distinct corr_name),
count(distinct corr_mod_name),
count(distinct correct_state_code),
count(distinct mod_eeduns),
count(distinct mod_parent),
count(distinct parent_id),
count(distinct agency_submission_date),
count(distinct recipient_loc_mismatch_flag),
count(distinct pop_loc_mismatch_flag),
count(distinct duns_mismatch_flag),
count(distinct cfda_mismatch_flag),
count(distinct eeparentduns),
count(distinct parentcompany),
count(distinct rei_created_date),
count(distinct rei_updated_date)
FROM faads_main;
