DATA_built = conjugate-gradient-drop.sql conjugate-gradient.sql sql/test.sql
MODULES = conjugate-gradient
PGXS := $(shell pg_config --pgxs)
include $(PGXS)
include config.mk
#CC=gcc -no-cpp-precomp -m64
#CC=gcc -no-cpp-precomp -m32
