DATA_built = conjugate-gradient-drop.sql conjugate-gradient.sql sql/test.sql
MODULES = cg_lib
PGXS := $(shell pg_config --pgxs)
include $(PGXS)
#CC=gcc -no-cpp-precomp -m64
#CC=gcc -no-cpp-precomp -m32
