-- Drop functions

DROP AGGREGATE madlib.mregr_coef(DOUBLE PRECISION, DOUBLE PRECISION[]);

DROP AGGREGATE madlib.mregr_r2(DOUBLE PRECISION, DOUBLE PRECISION[]);

DROP AGGREGATE madlib.mregr_tstats(DOUBLE PRECISION, DOUBLE PRECISION[]);

DROP AGGREGATE madlib.mregr_pvalues(DOUBLE PRECISION, DOUBLE PRECISION[]);

DROP FUNCTION madlib.float8_mregr_accum(DOUBLE PRECISION[], DOUBLE PRECISION, DOUBLE PRECISION[]);

DROP FUNCTION madlib.float8_mregr_combine(DOUBLE PRECISION[], DOUBLE PRECISION[]) CASCADE;

DROP FUNCTION FUNCTION madlib.float8_mregr_r2(DOUBLE PRECISION[]);

DROP FUNCTION madlib.float8_mregr_tstats(DOUBLE PRECISION[]);

DROP FUNCTION madlib.float8_mregr_pvalues(DOUBLE PRECISION[]);

DROP FUNCTION madlib.student_t_cdf(INTEGER, DOUBLE PRECISION);

-- For now, we do not drop sample data. At this point it is generated by the PGXS regression test and stored in schema madlib_examples.
