#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

FROM centos/postgresql-96-centos7:9.6

USER root

### Get postgres specific add-ons
RUN yum install -y \
                    gcc \
                    gcc-c++ \
                    wget \
                    postgresql-devel \
                    openssl \
                    m4 \
                    vim \
                    make \
                    java \
                    epel-release \
                    python-devel \
                    rh-postgresql96-postgresql-plpython

RUN yum install -y python-pip
ENV PATH="PATH=$PATH:/opt/rh/rh-postgresql96/root/usr/bin"
RUN pip install awscli pygresql paramiko --upgrade

## To build an image from this docker file without LaTex, from madlib folder, run:
## docker build -t madlib/centos_7_postgres_9.6:latest -f tool/docker/base/Dockerfile_centos_7_postgres_9_6 .
## To push it to docker hub, run:
## docker push madlib/centos_7_postgres_9.6:latest

## To build an image from this docker file with LaTex, from madlib folder, uncomment
## line 60, and run:
## docker build -t madlib/centos_7_postgres_9.6:LaTex -f tool/docker/base/Dockerfile_postgres_9_6 .
## To push it to docker hub, run:
## docker push madlib/centos_7_postgres_9.6:LaTex
